/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    GanttChart: typeof import('./src/components/gantt/GanttChart.vue')['default']
    GanttTaskList: typeof import('./src/components/gantt/GanttTaskList.vue')['default']
    GanttToolbar: typeof import('./src/components/gantt/GanttToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskComments: typeof import('./src/components/gantt/TaskComments.vue')['default']
  }
}
